apiVersion: v1
kind: Service
metadata:
  name: teemii-api
spec:
  selector:
    app: teemii-api
  type: LoadBalancer
  ports:
    - name: teemii-api
      protocol: TCP
      port: 3000
      targetPort: 3000
  loadBalancerIP: 192.168.20.209